version: 2.1

jobs:
  test:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: ./gradlew dependencies test
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
  publish:
    parameters:
      channel:
        description: "plugin repository channel to publish to"
        type: enum
        enum: ["alpha", "Stable"]
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: ./gradlew publishPlugin -PpublishChannel=<< parameters.channel >>

workflows:
  version: 2
  build-deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - publish:
          channel: "alpha"
          requires:
            - test
          filters:
            branches:
              only: /20\d\d\.\d-master/ # e.g. 2019.1-master
      - publish:
          channel: "Stable"
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /20\d\d\.\d\.\d/ # e.g. 2019.1.1
